### ISSUE TITLE
Inquiry Regarding Continued Maintenance and Related Research Publications

### ISSUE THREAD

**Issue by zhengh96** [domgurvic/CHASER#1]
Hello,

I hope this message finds you well.

I am writing to inquire whether this repository is still actively maintained. Additionally, I am interested in knowing if there have been any related research publications or papers that utilize or expand upon this work.

Your response would be greatly appreciated.

Thank you for your time and contributions!

Best regards,
Hang

**Comment by domgurvic** [comment]
Hi Hang, 

Thanks for your inquiry, I have added two publications to the README that are related to this work, for you to check out.

As it currently stands this repository is not actively maintained. 

Best, 

Dom.
